#!/bin/bash

export CH4RCH_SRC="$HOME/CH4rch_Linux"

export CH4RCH_BUILDROOT="/var/ch4rch-build"

export CH4RCH_WORK="$CH4RCH_BUILDROOT/workspaces"
export CH4RCH_ROOTFS="$CH4RCH_WORK/rootfs"

export CH4RCH_PKGDEST="$CH4RCH_BUILDROOT/pkgdest"
export CH4RCH_SRCDEST="$CH4RCH_BUILDROOT/srcdest"

export CH4RCH_REPO="$CH4RCH_BUILDROOT/repo"

export CH4RCH_LOGS="$CH4RCH_BUILDROOT/logs"
export CH4RCH_ISO="$CH4RCH_BUILDROOT/iso"

export CH4RCH_ARCH="x86_64"
export CH4RCH_REPO_NAME="core"

export MAKEFLAGS="-j$(nproc)"
export PKGEXT='.pkg.tar.zst'
